algoritmo "Par ou Impar"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : [Bruna Sozo]
// Descrição   : Identificar se o número é par ou impar
// Autor(a)    : Maria Clara Kalile
// Data atual  : 06/03/2025
var

N:inteiro

inicio

escreva ("Digite o número para descobrir se ele é par ou impar: ")
leia (N)
se (N%2=0) entao
    escreval ("O número é Par")
senao
    escreval ("O número é Impar")
fimse

fimalgoritmo
